[application]

[bundle]
identifier = "com.wingedcap.app"
publisher = "wingedcap"
icon = ["src/theme/icon.png"]

[web.app]

# HTML title tag content
title = "Wingedcap Server"

# include `assets` in web platform
[web.resource]

# Additional CSS style files
style = []

# Additional JavaScript files
script = []

[web.resource.dev]

# Javascript code file
# serve: [dev-server] only
script = []
